/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BatalhaNavall;

import static BatalhaNavall.Menu.nome1;
import static BatalhaNavall.Menu.nome2;
import BatalhaNavall.Posicao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class Tabuleiro extends javax.swing.JFrame {

    /**
     * Creates new form Tabuleiro
     */
    private static int turno;
    private static int vencedor1;
    private static int vencedor2;

    public Tabuleiro(String nomeJogador_1, String nomeJogador_2) {
        initComponents();
        inicializaJogadores();
        inicializaTabuleiro();
        preencheTabuleiro();
    }

    public void inicializaTabuleiro() {
        for (int i = 1; i < 10; i++) {
            for (int j = 0; j < 9; j++) {
                jTable1.setValueAt("", j, i);
                jTable2.setValueAt("", j, i);
            }
        }

    }

    public void preencheTabuleiro() {

        NavioVertical alocaV = new NavioVertical();
        NavioHorizontal alocaH = new NavioHorizontal();

        List<Integer> NavioV1 = new ArrayList<>();
        List<Integer> NavioV2 = new ArrayList<>();
        List<Integer> NavioV3 = new ArrayList<>();
        List<Integer> NavioV4 = new ArrayList<>();
        List<Integer> NavioH1 = new ArrayList<>();
        List<Integer> NavioH2 = new ArrayList<>();
        List<Integer> NavioH3 = new ArrayList<>();
        List<Integer> NavioH4 = new ArrayList<>();

        
        NavioV1 = alocaV.alocaNavio(2);
        NavioH1 = alocaH.alocaNavio(2);
        NavioV2 = alocaV.alocaNavio(2);
        NavioH2 = alocaH.alocaNavio(2);
        NavioV3 = alocaV.alocaNavio(3);
        NavioH3 = alocaH.alocaNavio(3);
        NavioV4 = alocaV.alocaNavio(4);
        NavioH4 = alocaH.alocaNavio(5);

        for (int i = 1; i < NavioV1.size(); i++) {
            jTable1.setValueAt("  ", NavioH1.get(0), NavioH1.get(i));
            jTable1.setValueAt("  ", NavioV1.get(i), NavioV1.get(0));
            jTable1.setValueAt("  ", NavioV2.get(i), NavioV2.get(0));
            jTable1.setValueAt("  ", NavioH2.get(0), NavioH2.get(i));
        }
        for (int i = 1; i < NavioV3.size(); i++) {

            jTable1.setValueAt("  ", NavioH3.get(0), NavioH3.get(i));
            jTable1.setValueAt("  ", NavioV3.get(i), NavioV3.get(0));
            
        }
        for (int i = 1; i < NavioV4.size(); i++) {
            jTable1.setValueAt("  ", NavioV4.get(i), NavioV4.get(0));
        }
        for (int i = 1; i < NavioH4.size(); i++) {
            jTable1.setValueAt("  ", NavioH4.get(0), NavioH4.get(i));

        }

        NavioV1 = alocaV.alocaNavio(2);
        NavioH1 = alocaH.alocaNavio(2);
        NavioV2 = alocaV.alocaNavio(2);
        NavioH2 = alocaH.alocaNavio(2);
        NavioV3 = alocaV.alocaNavio(3);
        NavioH3 = alocaH.alocaNavio(3);
        NavioV4 = alocaV.alocaNavio(4);
        NavioH4 = alocaH.alocaNavio(5);

        for (int i = 1; i < NavioV1.size(); i++) {
            jTable2.setValueAt("  ", NavioH1.get(0), NavioH1.get(i));
            jTable2.setValueAt("  ", NavioV1.get(i), NavioV1.get(0));
            jTable2.setValueAt("  ", NavioV2.get(i), NavioV2.get(0));
            jTable2.setValueAt("  ", NavioH2.get(0), NavioH2.get(i));
        }
        for (int i = 1; i < NavioV3.size(); i++) {

            jTable2.setValueAt("  ", NavioH3.get(0), NavioH3.get(i));
            jTable2.setValueAt("  ", NavioV3.get(i), NavioV3.get(0));
            
        }
        for (int i = 1; i < NavioV4.size(); i++) {
            jTable2.setValueAt("  ", NavioV4.get(i), NavioV4.get(0));
        }
        for (int i = 1; i < NavioH4.size(); i++) {
            jTable2.setValueAt("  ", NavioH4.get(0), NavioH4.get(i));

        }

    }

    public void inicializaJogadores() {
        turno = 0;
        vencedor1 = 0;
        vencedor2 = 0;
        Jogadores.setNomes();
        nomeJogador1.setText(Jogadores.getNome1());
        nomeJogador2.setText(Jogadores.getNome2());

    }

    public boolean verificaTurno() {
        if (turno % 2 == 0) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        campotexto2 = new javax.swing.JTextField();
        campoTexto1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        nomeJogador1 = new javax.swing.JLabel();
        nomeJogador2 = new javax.swing.JLabel();

        jScrollPane3.setViewportView(jTextPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalha Naval");
        setBackground(new java.awt.Color(0, 102, 102));
        setBounds(new java.awt.Rectangle(0, 0, 800, 600));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null, null, null, null, null, null},
                {"2", null, null, null, null, null, null, null, null, null},
                {"3", null, null, null, null, null, null, null, null, null},
                {"4", null, null, null, null, null, null, null, null, null},
                {"5", null, null, null, null, null, null, null, null, null},
                {"6", null, null, null, null, null, null, null, null, null},
                {"7", null, null, null, null, null, null, null, null, null},
                {"8", null, null, null, null, null, null, null, null, null},
                {"9", null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "A", "B", "C", "D", "E", "F", "G", "H", "I"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null, null, null, null, null, null},
                {"2", null, null, null, null, null, null, null, null, null},
                {"3", null, null, null, null, null, null, null, null, null},
                {"4", null, null, null, null, null, null, null, null, null},
                {"5", null, null, null, null, null, null, null, null, null},
                {"6", null, null, null, null, null, null, null, null, null},
                {"7", null, null, null, null, null, null, null, null, null},
                {"8", null, null, null, null, null, null, null, null, null},
                {"9", null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "A", "B", "C", "D", "E", "F", "G", "H", "I"
            }
        ));
        jTable2.setRowHeight(25);
        jScrollPane2.setViewportView(jTable2);

        campotexto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotexto2ActionPerformed(evt);
            }
        });

        campoTexto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTexto1ActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jTextPane2);

        nomeJogador1.setText("jLabel1");

        nomeJogador2.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(57, 57, 57)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(nomeJogador1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(289, 289, 289))
                    .add(layout.createSequentialGroup()
                        .add(campoTexto1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(108, 108, 108)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(campotexto2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nomeJogador2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(291, 291, 291))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 37, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 254, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 254, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nomeJogador1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nomeJogador2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(campoTexto1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(campotexto2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Tratar exceção
    //
    //
    //
    private void campotexto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotexto2ActionPerformed

        if (!verificaTurno()) {
            jTextPane2.setText("");
            try {
                char[] tabela1 = new char[2];
                String jogada1 = campotexto2.getText();
                jogada1.getChars(0, 2, tabela1, 0);
                if (jogada1.length() < 3) {
                    int y = (int) tabela1[0] - 64;
                    int x = (int) tabela1[1] - 49;
                    if ((!jTable1.getValueAt(x, y).equals("  X")) && (!jTable1.getValueAt(x, y).equals("   /"))) {
                        turno++;
                    } else {
                        jTextPane2.setText("Não repita posições");
                    }
                    if (jTable1.getValueAt(x, y).equals("  ")) {
                        jTable1.setValueAt("  X", x, y);
                        vencedor1++;
                        if (vencedor1 == 23) {
                            JOptionPane.showMessageDialog(null, " parabéns " + nomeJogador2.getText() + " venceu ");
                            this.setVisible(false);
                           ManipulaArquivo a1 = new ManipulaArquivo(vencedor1,vencedor2,nomeJogador1.getText(),nomeJogador2.getText());
                           a1.setVisible(true);
                        }
                    } else if (!jTable1.getValueAt(x, y).equals("  X")) {
                        jTable1.setValueAt("   /", x, y);
                    }
                } else {
                    jTextPane2.setText("Digite uma posição valida");
                }
            } catch (Exception e) {
                jTextPane2.setText("Digite uma posição valida");
            }
        } else {
            jTextPane2.setText("TURNO DO JOGADOR 1");
        }
    }//GEN-LAST:event_campotexto2ActionPerformed

    private void campoTexto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTexto1ActionPerformed
        if (verificaTurno()) {
            jTextPane2.setText("");
            try {
                char[] tabela2 = new char[2];
                String jogada2 = campoTexto1.getText();
                jogada2.getChars(0, 2, tabela2, 0);
                if (jogada2.length() < 3) {
                    jTextPane2.setText("");
                    int y2 = (int) tabela2[0] - 64;
                    int x2 = (int) tabela2[1] - 49;
                    if ((!jTable2.getValueAt(x2, y2).equals("  X")) && (!jTable2.getValueAt(x2, y2).equals("   /"))) {
                        turno++;
                    } else {
                        jTextPane2.setText("Não repita posições");
                    }
                    if (jTable2.getValueAt(x2, y2).equals("  ")) {
                        jTable2.setValueAt("  X", x2, y2);
                        vencedor2++;
                        if (vencedor2 == 23) {
                            JOptionPane.showMessageDialog(null, " Parabéns " + nomeJogador1.getText() + " venceu ");
                            this.setVisible(false);
                            ManipulaArquivo a1 = new ManipulaArquivo(vencedor1,vencedor2,nomeJogador1.getText(),nomeJogador2.getText());
                            a1.setVisible(true);
                        }
                    } else if (!jTable2.getValueAt(x2, y2).equals("  X")) {
                        jTable2.setValueAt("   /", x2, y2);
                    }
                } else {
                    jTextPane2.setText("Digite uma posição valida");
                }
            } catch (Exception e) {
                jTextPane2.setText("Digite uma posição valida");
            }
            System.out.println(turno);
        } else {
            jTextPane2.setText("TURNO DO JOGADOR 2");
        }

    }//GEN-LAST:event_campoTexto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabuleiro().setVisible(true);
            }
        });
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTexto1;
    private javax.swing.JTextField campotexto2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JLabel nomeJogador1;
    private javax.swing.JLabel nomeJogador2;
    // End of variables declaration//GEN-END:variables

}
